name: multi_step_widgets
description: Widgets for building multi-step flows, forms, and wizards
version: 0.2.0
homepage: https://github.com/yourusername/multi_step_widgets
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  multi_step_flow:

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
