name: multi_step_widgets
description: Flutter UI widgets for building multi-step flows with customizable indicators, navigation controls, and layouts
version: 0.1.0+2
homepage: https://github.com/egyleader/multi_step

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  multi_step_flow:
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
