name: multi_step

packages:
  - packages/**

ignore:
  - 'packages/**/example'

scripts:
  ffmt:
    exec: dart fix --apply && dart format .
    description: Fix and format Dart code for all packages
  fgen:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build runner with override for all packages
