name: multi_step_flow
description: A platform-agnostic solution for managing multi-step flows with support for different flow types, validation, and customization.
version: 1.0.0
repository: https://github.com/egyleader/multi_step

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.7.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
