name: multi_step_example
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  multi_step_flow:
    path: ../../multi_step_flow
  multi_step_widgets:
    path: ../../multi_step_widgets

  cupertino_icons: ^1.0.8

  flutter_bloc: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


  flutter_bloc: any
flutter:

  uses-material-design: true


dependency_overrides:
  multi_step_flow:
    path: ../../multi_step_flow


